---
title: "Pierre Brasseur"
---

# Sociologue \| Chargé de Cours et Professeur à l'Université Libre de Bruxelles

### Affiliations et Postes

-   Chercheur au Centre METICES (depuis septembre 2024)

-   Professeur à l'Université Libre de Bruxelles (ULB)

-   Ancien membre du comité exécutif de l'Association française de
    sociologie

-   Ex-directeur du groupe "Éthique professionnelle"

-   Ex-responsable du réseau thématique "Recherches en sciences sociales
    sur la sexualité"

### Localisation

-   Campus de Charleroi : 31, blvd Solvay, 6000 Charleroi (Zénobe
    Gramme - Entrée rue Lebeau)

-   Campus du Solbosch Bruxelles : Avenue Jeanne 44 (CP 124), 1050
    Bruxelles (Bât.S, 13e étage - Bureau S13.129)

### Contact

Email : [pierre.brasseur\@ulb.be](mailto:pierre.brasseur@ulb.be)

### Domaines d'expertise

-   Genre et sexualité

-   Handicap

-   Sociologie du travail

-   Inégalités sociales

-   Sciences sociales de l'enfance

-   Violence sexiste et sexuelle dans le sport

-   Santé

-   Numérique

-   Pornographie

-   Émotion

-   Éthique de la Recherche

### Enseignements (ULB, Charleroi)

1.  Théorie du travail social (Master en sciences du travail, spécialité
    "travail social et non marchand")

2.  Mobilisations, genre et identités professionnelles (Master en
    sciences du travail)

3.  Méthodes de recherche en sciences humaines

4.  Care au travail : famille, santé (à partir de 2024)

### Axes de recherche

-   Sexualité au travail

-   Orientation sexuelle comme variable scientifique

-   Travail dans les lieux d'enfermement

-   Éducation à la sexualité et à l'égalité des sexes

-   Sciences de l'enfance

-   Méthodes de recherche en terrains sensibles

### Publications notables

1.  **Livre** :

    -   "Sociologie de l'assistance sexuelle : Former et transformer la
        sexualité" (Presses universitaires de France, 2023)

2.  **Articles dans des Revues académiques** (sélection) :

    -   "Comment peut-on dire la sexualité ?" (Terrains et Travaux,
        2022)

    -   "L'espace contemporain de la formation en sociologie en France :
        une cartographie à construire" (Socio-logos, 2021)

    -   "Les économies de la sexualité" (Revue française de
        Socio-Économie, 2020)

3.  **Direction de Revues scientifiques** :

    -   "Dire la sexualité", Terrains & Travaux, n° 40, 2022

    -   "Formation: sociologue", Socio-logos, 15, 2021

    -   "Handicap, genre et sexualité", Genre, sexualité & société, 19,
        2018

4.  **Chapitres d'Ouvrages et Encyclopédie** :

    -   "Les assistantes sexuelles, des travailleuses du sexe ?" (2023)

    -   "Handicap" dans l'Encyclopédie critique du genre (2021)

5.  **Thèse** :

    -   "L'invention de l'assistance sexuelle : sociohistoire d'un
        problème public français" (Université de Lille, 2017)

### Supervision de recherche

Pierre Brasseur supervise des mémoires et des thèses en sociologie sur
des thèmes tels que le handicap, la santé, la sexualité, le travail
domestique et les questions LGBT. Les étudiants intéressés sont invités
à soumettre leur CV et un projet de recherche (2 pages max) à
[pierre.brasseur\@ulb.be](mailto:pierre.brasseur@ulb.be).

### Profils académiques

-   Google Scholar :
    [Profil](https://scholar.google.fr/citations?user=O4AvHvkAAAAJ&hl=fr)

-   ResearchGate :
    [Profil](https://www.researchgate.net/profile/Pierre-Brasseur-3)

Pour plus d'informations sur ses publications, interventions et détails
des cours, consultez sa page sur le site de l'ULB.
