---
title: "Enseignement"
---

### **Activités d'enseignement**

Les syllabus de mes cours sont disponibles sur mon site internet
[pierrebrasseur.fr](http://pierrebrasseur.fr). Plusieurs exemples de
contenu pédagogique sont fournis en annexe.

J'ai enseigné plus de **1 000 heures** dans divers établissements,
notamment à l'Université de Lille, Paris 13, Nanterre, Brest,
Saint-Étienne, Toulouse, à l'Institut Catholique de Paris, l'Université
Paris Descartes, Créteil, et Grenoble.

#### **Cours de Licence 1 :**

-   **Socialisation** (S1, S2) — Institut Catholique de Paris (Licence
    Sciences Sociales)\
    Cours magistral (CM) : 100 étudiants - 48 heures (2x8 séances de
    3h)\
    *2021-2023, CDD*

-   **Auteurs et concepts** — Lille 1 (Responsables : Anne Bory, Cécile
    Vignal)\
    Travaux dirigés (TD) : 40 étudiants - 240 heures (3 groupes, 10
    séances)\
    *2013-2016, Avenant et ATER*

-   **Méthodologie du travail universitaire** — Lille 1\
    TD : 40 étudiants - 195 heures (3 groupes, 10 séances de 1h30)\
    *2013-2016, Avenant et ATER*

#### **Cours de Licence 2 :**

-   **Rapports sociaux de sexe** — Université Lille 1\
    CM : 100 étudiants - 48 heures (2 séances de 2h)\
    *2013-2017, Avenant, ATER et vacataire*

-   **Sociologie du handicap** — Université de Saint-Étienne\
    CM : 75 étudiants - 24 heures (8 séances de 3h)\
    *2021-2022, Vacataire*

#### **Cours de Licence 3 :**

-   **Sociologie politique de la dépendance** — Université Paris
    Descartes\
    CM : 50 étudiants - 24 heures (8 séances de 3h)\
    *2021-2023, CDD*

-   **Sociologie du genre et de la santé** — Université Paris 13\
    CM : 150 étudiants (2 promotions) - 126 heures (7 séances de 3h x
    2)\
    *2019-2023, Vacataire*

#### **Cours de Master 1 :**

-   **Sociologie du handicap** — Université de Grenoble (Master
    Vieillissement, Handicap, Santé et Inégalités)\
    CM : 40 étudiants - 24 heures (8 séances de 3h)\
    *2021-2022, Vacataire*

-   **Sociologie de la sexualité dans le champ du handicap** —
    Université de Brest\
    CM : 50 étudiants - 18 heures (1 séance de 6h)\
    *2017, 2020, 2022, Vacataire*

#### **Cours de Master 2 :**

-   **Sociologie des émotions** — Université Lille 1 (Master Pratiques
    et Politiques locales de Santé)\
    CM : 15 étudiants - 45 heures (3 séances de 3h)\
    *2013-2016, Avenant et ATER*

-   **Sociologie de la sexualité** — Université Toulouse 2 (Master
    Éducation à la Sexualité Humaine)\
    CM : 30 étudiants - 72 heures (3 séances de 6h)\
    *2019-2023, Vacataire*

-   **Sociohistoire des politiques sociales** — Université Paris
    Dauphine (Master Management Stratégie des Services et Établissements
    pour Personnes Âgées)\
    CM : 15 étudiants - 24 heures (8 séances de 3h)\
    *2021-2023, Vacataire*

-   **Sociologie du numérique** — Université Lille (Master Études
    Numériques et Statistiques Publiques)\
    CM : 12 heures (4 séances de 4h)\
    *2022-2023, Vacataire*

#### **Autres enseignements :**

-   **Sociologie du handicap** — Université Saint-Étienne, Paris
    Diderot, DIU\
    CM : 30 étudiants - 3 heures\
    *2021-2023, Vacataire*

-   **Sociologie de la santé et de la sexualité** — Université Toulouse
    (Master AGAPES)\
    CM : 12 heures (2 séances de 6h)\
    *2022-2023, Vacataire*
