---
title: "Graham"
format: revealjs
---

# Critique de la séparation dans les sciences sociales

Graham critique la tendance des sciences sociales à séparer
artificiellement ces deux dimensions :

a\) Approches psychologiques :

-   Se concentrent sur l'aspect émotionnel du "care"

-   Décrivent le "care" comme une qualité inhérente aux femmes.

-   Influencées par des théories psychodynamiques (ex: Nancy Chodorow)

-   Risquent d'essentialiser le rôle de "care" des femmes

b\) Approches en politique sociale :

-   Mettent l'accent sur la dimension matérielle du "care"

-   Décrivent le "care" comme une contribution économique non rémunérée.

-   Influencées par le marxisme-féminisme

-   Réduire le "care" à une simple transaction matérielle

3.  Complexité du "care"

Graham souligne que dans la pratique, les aspects émotionnels et
matériels sont interconnectés. Elle donne des exemples :

-   Une mère soignant un enfant malade : fournit des soins physiques et
    un soutien émotionnel.

-   Une personne s'occupant d'un parent âgé : effectue des tâches
    physiques et offre un soutien affectif.

4.  
