---
title: "site"
---

### **Activités de recherche :**

-   **2022** : **Santé mentale et environnement**\
    Projet mené à Arènes (Université Rennes 1, EHESP), co-porté avec
    Jean-Pierre Le Bourhis, Stève Bernardin et Nathalie Berny.

    -   Réalisation de 30 entretiens avec des agents de la fonction
        publique.

-   **2017** : **Les travailleurs de l’intime sur internet : marchés et
    santé sexuelle**\
    Projet mené à l'Université de Grenoble (ANR-IDEX), co-porté avec
    Jean Finez.

    -   Réalisation de 50 entretiens semi-directifs.

-   **2022** : **Se suicider pendant le Covid**\
    Projet postdoctoral en collaboration avec Guillaume Vaiva et
    Marielle Wathelet.

    -   Réalisation de 40 entretiens avec des professionnels de la santé
        mentale.

-   **2019** : **Inégalités sociales de handicap : emploi et aides
    techniques**\
    Co-porté avec Sylvain Pichetti (IRDES) et Emmanuelle Leray (EHESP).

    -   Réalisation de 30 entretiens semi-directifs avec des personnes
        atteintes de sclérose en plaques et enquête sur le financement
        des aides techniques au Canada, en Suède et au Royaume-Uni.

-   **2022** : **Santé sexuelle, jeunes et handicap**\
    Projet mené en collaboration avec INSERM-INED, sous la direction
    de P. Martin et E. de La Rochebrochard.

-   **2020** : **Handicap et traumatisme crânien**\
    Projet en collaboration avec l'IRESP, INSERM et l'Université
    Toulouse 2 (Anita Mediani). Étude des tensions entre aides humaines
    et aides techniques, en collaboration avec François Sicot.

-   **2019** : **Inégalités sociales de santé et maladie de Crohn**\
    Projet mené à Lille 3, sous la direction de Béatrice Touchelay.

------------------------------------------------------------------------
